"""Dataset-aware suggested questions.

Deliberately **deterministic**: suggestions are derived from the schema by
rules, not generated by the LLM. They appear on page load, so an API call here
would cost a request (and a wait) before the user has asked anything — and the
rules produce better-grounded suggestions anyway, because they only propose
questions the executor can actually answer.

The rules work in two layers: a semantic layer that recognises common business
fields by name (revenue, churn, region, satisfaction) and produces specific,
natural questions; and a structural fallback driven purely by column roles, so
an unfamiliar dataset still gets useful prompts.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Iterable

import pandas as pd

from app.models.profile import DatasetProfile
from app.tools.charts import lower_label
from app.tools.resolution import normalize
from app.tools.validation import (
    categorical_columns,
    datetime_columns,
    numeric_columns,
    require_dataframe,
)

#: How many suggestions to offer.
MIN_SUGGESTIONS = 4
MAX_SUGGESTIONS = 6

#: Semantic roles recognised by column name, mapped to the tokens that imply
#: them. Matching is on the normalised name, so "monthly_charges" and
#: "MonthlyCharge" both land on `charge`.
SEMANTIC_TOKENS: dict[str, tuple[str, ...]] = {
    "revenue": ("revenue", "sale", "income", "turnover", "amount", "total_revenue"),
    "charge": ("charge", "price", "bill", "fee", "cost", "arpu", "mrr"),
    "churn": ("churn", "churned", "attrition", "cancelled", "lost"),
    "satisfaction": ("satisfaction", "satisfaction_score", "csat", "nps", "rating"),
    "support": ("support_call", "support", "ticket", "complaint", "call"),
    "tenure": ("tenure", "tenure_month", "month_active", "age_day", "seniority"),
    "usage": ("usage", "data_usage", "consumption", "volume"),
    "region": ("region", "area", "territory", "zone", "market", "country", "state"),
    "city": ("city", "town", "branch", "store", "location"),
    "contract": ("contract", "contract_type", "subscription", "agreement"),
    "product": ("product", "product_type", "service", "sku", "category", "item"),
    "network": ("network", "network_type", "technology", "platform", "channel"),
    "payment": ("payment", "payment_method", "billing"),
}


@dataclass
class DatasetRoles:
    """Which semantic and structural fields a dataset offers."""

    numeric: list[str]
    categorical: list[str]
    dates: list[str]
    semantic: dict[str, str]

    def has(self, *roles: str) -> bool:
        return all(role in self.semantic for role in roles)

    def column(self, role: str) -> str | None:
        return self.semantic.get(role)

    @property
    def primary_measure(self) -> str | None:
        """The most answer-worthy numeric column."""
        for role in ("revenue", "charge", "usage"):
            column = self.semantic.get(role)
            if column:
                return column
        return self.numeric[0] if self.numeric else None

    @property
    def primary_dimension(self) -> str | None:
        for role in ("region", "product", "contract", "network", "city"):
            column = self.semantic.get(role)
            if column:
                return column
        return self.categorical[0] if self.categorical else None


def detect_roles(df: pd.DataFrame) -> DatasetRoles:
    """Classify a dataset's columns structurally and semantically."""
    require_dataframe(df)

    numeric = numeric_columns(df)
    categorical = categorical_columns(df, max_unique=200)
    dates = datetime_columns(df)

    # Booleans are both a measure (a rate, when averaged) and a grouping field.
    booleans = [
        str(c) for c in df.columns
        if str(c) not in numeric
        and df[c].dropna().nunique() == 2
        and str(c) in categorical
    ]

    semantic: dict[str, str] = {}
    for column in df.columns:
        name = normalize(str(column))
        tokens = set(name.split("_"))
        for role, markers in SEMANTIC_TOKENS.items():
            if role in semantic:
                continue
            for marker in markers:
                marker_tokens = set(normalize(marker).split("_"))
                if marker_tokens <= tokens or normalize(marker) == name:
                    semantic[role] = str(column)
                    break

    # A churn flag is a measure even though it reads as a category.
    churn = semantic.get("churn")
    if churn and churn not in numeric:
        numeric = [*numeric, churn]

    return DatasetRoles(
        numeric=numeric,
        categorical=[c for c in categorical if c not in booleans] + booleans,
        dates=dates,
        semantic=semantic,
    )


# --------------------------------------------------------------------------- #
# Rules
# --------------------------------------------------------------------------- #

Rule = Callable[[DatasetRoles], list[str]]


def _rule_revenue_trend(roles: DatasetRoles) -> list[str]:
    measure = roles.column("revenue") or roles.column("charge")
    if not (measure and roles.dates):
        return []
    label = lower_label(measure)
    return [
        f"How has {label} changed over time?",
        f"Which month generated the highest {label}?",
        f"Compare {label} in the latest quarter with the previous quarter.",
    ]


def _rule_revenue_by_dimension(roles: DatasetRoles) -> list[str]:
    measure = roles.column("revenue")
    dimension = roles.column("region") or roles.column("product")
    if not (measure and dimension):
        return []
    return [f"Which {lower_label(dimension)} generated the most {lower_label(measure)}?"]


def _rule_churn(roles: DatasetRoles) -> list[str]:
    churn = roles.column("churn")
    if not churn:
        return []
    out: list[str] = []
    grouping = roles.column("contract") or roles.column("product") or roles.primary_dimension
    if grouping and grouping != churn:
        out.append(f"Which {lower_label(grouping)} has the highest churn rate?")
    if len(roles.numeric) > 1:
        out.append("Which numeric factors are most associated with churn?")
    return out


def _rule_support_satisfaction(roles: DatasetRoles) -> list[str]:
    if not roles.has("support", "satisfaction"):
        return []
    support = roles.column("support")
    satisfaction = roles.column("satisfaction")
    return [
        f"How does {lower_label(satisfaction)} vary with "
        f"{lower_label(support)} volume?"
    ]


def _rule_charge_comparison(roles: DatasetRoles) -> list[str]:
    charge = roles.column("charge")
    grouping = roles.column("contract") or roles.column("network") or roles.column("product")
    if not (charge and grouping):
        return []
    return [
        f"Compare average {lower_label(charge)} by {lower_label(grouping)}.",
        f"Show the distribution of {lower_label(charge)}.",
    ]


def _rule_counts(roles: DatasetRoles) -> list[str]:
    dimension = roles.column("network") or roles.column("region") or roles.primary_dimension
    if not dimension:
        return []
    return [f"How many records are in each {lower_label(dimension)}?"]


def _rule_correlation(roles: DatasetRoles) -> list[str]:
    if len(roles.numeric) < 3:
        return []
    measure = roles.primary_measure
    out = ["Which numerical variables are most strongly correlated?"]
    if measure:
        out.append(
            f"Which numerical variables correlate most strongly with "
            f"{lower_label(measure)}?"
        )
    return out


def _rule_segment_behaviour(roles: DatasetRoles) -> list[str]:
    dimension = roles.column("region") or roles.column("city")
    measure = roles.primary_measure
    if not (dimension and measure):
        return []
    return [
        f"Compare average {lower_label(measure)} across "
        f"{lower_label(dimension)} values."
    ]


def _rule_outliers(roles: DatasetRoles) -> list[str]:
    measure = roles.primary_measure
    if not measure:
        return []
    return [f"Are there any unusual values in {lower_label(measure)}?"]


def _rule_structural(roles: DatasetRoles) -> list[str]:
    """Fallbacks for an unfamiliar dataset, driven only by column roles."""
    out: list[str] = []
    measure = roles.primary_measure
    dimension = roles.primary_dimension

    if measure and dimension:
        out.append(
            f"Which {lower_label(dimension)} has the highest average "
            f"{lower_label(measure)}?"
        )
    if measure and roles.dates:
        out.append(
            f"Show {lower_label(measure)} over time by month."
        )
    if dimension:
        out.append(f"How many records are in each {lower_label(dimension)}?")
    if measure:
        out.append(f"Summarise {lower_label(measure)}.")
    out.append("What does this dataset contain?")
    return out


#: Rules in priority order; earlier suggestions win a contested slot.
RULES: tuple[Rule, ...] = (
    _rule_revenue_by_dimension,
    _rule_churn,
    _rule_revenue_trend,
    _rule_charge_comparison,
    _rule_correlation,
    _rule_support_satisfaction,
    _rule_counts,
    _rule_segment_behaviour,
    _rule_outliers,
    _rule_structural,
)


def suggest_questions(
    df: pd.DataFrame,
    profile: DatasetProfile | None = None,
    *,
    limit: int = MAX_SUGGESTIONS,
) -> list[str]:
    """Four to six questions this dataset can actually answer.

    Deterministic: the same dataset always yields the same suggestions, and no
    API call is made.
    """
    require_dataframe(df)
    if df.empty or not len(df.columns):
        return ["What does this dataset contain?"]

    roles = detect_roles(df)
    suggestions: list[str] = []
    seen: set[str] = set()
    target = max(limit, MIN_SUGGESTIONS)

    # Two passes with a per-rule cap, so one prolific rule cannot fill the
    # whole list with variations on a single theme.
    for cap in (2, len(RULES)):
        for rule in RULES:
            taken = 0
            for question in rule(roles):
                if taken >= cap:
                    break
                key = question.lower()
                if key in seen:
                    continue
                seen.add(key)
                suggestions.append(question)
                taken += 1
                if len(suggestions) >= target:
                    return suggestions[:limit]

    if not suggestions:
        suggestions = ["What does this dataset contain?"]
    return suggestions[:limit]


def follow_up_questions(
    df: pd.DataFrame, *, exclude: Iterable[str] = (), limit: int = 3
) -> list[str]:
    """Deterministic follow-ups, used when the LLM supplies none."""
    taken = {q.lower().strip() for q in exclude}
    return [
        question
        for question in suggest_questions(df, limit=MAX_SUGGESTIONS)
        if question.lower().strip() not in taken
    ][:limit]


__all__ = [
    "MAX_SUGGESTIONS",
    "MIN_SUGGESTIONS",
    "RULES",
    "SEMANTIC_TOKENS",
    "DatasetRoles",
    "detect_roles",
    "follow_up_questions",
    "suggest_questions",
]
